// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository.Context;

namespace AlmassarGateApi.Repository.Migrations
{
    [DbContext(typeof(AlmassarGateContext))]
    partial class AlmassarGateContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AlmassarGate.Domain.Models.Common.Lookup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ModifiedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ParentId")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ModifiedById");

                    b.ToTable("Lookups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Key = "specsFileName",
                            ParentId = 2,
                            Status = 1,
                            Value = 1
                        },
                        new
                        {
                            Id = 2,
                            Key = "layoutFileName",
                            ParentId = 2,
                            Status = 1,
                            Value = 2
                        },
                        new
                        {
                            Id = 3,
                            Key = "paymentTermsFileName",
                            ParentId = 2,
                            Status = 1,
                            Value = 3
                        },
                        new
                        {
                            Id = 4,
                            Key = "numberOfPanels",
                            ParentId = 2,
                            Status = 1,
                            Value = 4
                        },
                        new
                        {
                            Id = 5,
                            Key = "designReference",
                            ParentId = 2,
                            Status = 1,
                            Value = 5
                        },
                        new
                        {
                            Id = 6,
                            Key = "projectName",
                            ParentId = 2,
                            Status = 1,
                            Value = 6
                        },
                        new
                        {
                            Id = 7,
                            Key = "clientName",
                            ParentId = 2,
                            Status = 1,
                            Value = 7
                        },
                        new
                        {
                            Id = 8,
                            Key = "projectGuid",
                            ParentId = 2,
                            Status = 1,
                            Value = 8
                        },
                        new
                        {
                            Id = 9,
                            Key = "technicalProposalFileName",
                            ParentId = 2,
                            Status = 1,
                            Value = 9
                        },
                        new
                        {
                            Id = 10,
                            Key = "financialProposalFileName",
                            ParentId = 2,
                            Status = 1,
                            Value = 10
                        },
                        new
                        {
                            Id = 11,
                            Key = "subStatus",
                            ParentId = 2,
                            Status = 1,
                            Value = 11
                        },
                        new
                        {
                            Id = 12,
                            Key = "technicalProposalProof",
                            ParentId = 2,
                            Status = 1,
                            Value = 12
                        },
                        new
                        {
                            Id = 13,
                            Key = "financialProposalProof",
                            ParentId = 2,
                            Status = 1,
                            Value = 13
                        },
                        new
                        {
                            Id = 14,
                            Key = "ironPhaseStartDate",
                            ParentId = 2,
                            Status = 1,
                            Value = 14
                        },
                        new
                        {
                            Id = 15,
                            Key = "ironPhaseEndDate",
                            ParentId = 2,
                            Status = 1,
                            Value = 15
                        },
                        new
                        {
                            Id = 16,
                            Key = "electricityPhaseStartDate",
                            ParentId = 2,
                            Status = 1,
                            Value = 16
                        },
                        new
                        {
                            Id = 17,
                            Key = "electricityPhaseEndDate",
                            ParentId = 2,
                            Status = 1,
                            Value = 17
                        },
                        new
                        {
                            Id = 18,
                            Key = "projectStartDate",
                            ParentId = 2,
                            Status = 1,
                            Value = 18
                        },
                        new
                        {
                            Id = 19,
                            Key = "projectEndDate",
                            ParentId = 2,
                            Status = 1,
                            Value = 19
                        });
                });

            modelBuilder.Entity("AlmassarGateApi.Domain.Models.Part", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Available")
                        .HasColumnType("int");

                    b.Property<long?>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ModifiedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PartName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PriceForUnit")
                        .HasColumnType("float");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ModifiedById");

                    b.ToTable("Parts");
                });

            modelBuilder.Entity("AlmassarGateApi.Domain.Models.ProjectFiles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FileCategory")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ModifiedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectFiles");
                });

            modelBuilder.Entity("Domains.Models.Action", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ActionType")
                        .HasColumnType("int");

                    b.Property<int>("ApprovalId")
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ModifiedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ModifiedById");

                    b.ToTable("Actions");
                });

            modelBuilder.Entity("Domains.Models.ApplicationExceptions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InnerException")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoggedInUser")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("StackTrace")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ApplicationExceptions");
                });

            modelBuilder.Entity("Domains.Models.ApplicationUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RegId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("([NormalizedUserName] IS NOT NULL)");

                    b.ToTable("ApplicationUser");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "83532a81-1d3d-434e-93a4-5728210ae2d7",
                            Email = "Mahmoud-Al-Massri@hotmail.com",
                            EmailConfirmed = false,
                            IsActive = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "Mahmoud-Al-Massri@hotmail.com",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAEAACcQAAAAELr73GmhxCifQepLABo6ilVa+fVkEu+M40P4tfg2C5xiBxeEROKT2xfyxcIoU57roQ==",
                            PhoneNumber = "0790809158",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "RCWSSGGSUGXLM4LBICRGPK75IGT77DIY",
                            TwoFactorEnabled = false,
                            UserName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Domains.Models.Approval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("ActionDate")
                        .HasColumnType("datetime");

                    b.Property<long?>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ModifiedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReceivedDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("ProjectId");

                    b.HasIndex("TaskId");

                    b.ToTable("Approval");
                });

            modelBuilder.Entity("Domains.Models.AspNetUserTokens", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Domains.Models.ChecklistAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Answer")
                        .HasColumnType("int");

                    b.Property<int>("ApprovalId")
                        .HasColumnType("int");

                    b.Property<int>("ChecklistQuestionId")
                        .HasColumnType("int");

                    b.Property<long?>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ModifiedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalId");

                    b.HasIndex("ChecklistQuestionId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ModifiedById");

                    b.ToTable("ChecklistAnswer");
                });

            modelBuilder.Entity("Domains.Models.ChecklistQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GroupTitleId")
                        .HasColumnType("int");

                    b.Property<long?>("ModifiedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("QuestionEnumId")
                        .HasColumnType("int");

                    b.Property<string>("QuestionProperties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ModifiedById");

                    b.ToTable("ChecklistQuestion");
                });

            modelBuilder.Entity("Domains.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<long?>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<long?>("ModifiedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("RoleId");

                    b.ToTable("Group");
                });

            modelBuilder.Entity("Domains.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClientName")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<long?>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DesignReference")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<DateTime?>("ElectricityPhaseEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ElectricityPhaseStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FilledPanels")
                        .HasColumnType("int");

                    b.Property<string>("FinancialProposalFileName")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("FinancialProposalProof")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("IronPhaseEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("IronPhaseStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LayoutFileName")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<long?>("ModifiedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NumberOfPanels")
                        .HasColumnType("int");

                    b.Property<string>("PaymentTermsFileName")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<DateTime?>("ProjectEndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProjectGuid")
                        .HasColumnName("ProjectGUID")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("ProjectInputId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectName")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<DateTime?>("ProjectStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SpecsFileName")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("SubStatus")
                        .HasColumnType("int");

                    b.Property<string>("TechnicalProposalFileName")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("TechnicalProposalProof")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ModifiedById");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("Domains.Models.RoleClaims", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("Domains.Models.Roles", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("([NormalizedName] IS NOT NULL)");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Admin",
                            NormalizedName = "Admin"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Client",
                            NormalizedName = "Client"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Production",
                            NormalizedName = "Production"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Design",
                            NormalizedName = "Design"
                        },
                        new
                        {
                            Id = 5L,
                            Name = "Repository",
                            NormalizedName = "Repository"
                        },
                        new
                        {
                            Id = 6L,
                            Name = "QC",
                            NormalizedName = "QC"
                        },
                        new
                        {
                            Id = 7L,
                            Name = "QA",
                            NormalizedName = "QA"
                        },
                        new
                        {
                            Id = 8L,
                            Name = "Sales",
                            NormalizedName = "Sales"
                        },
                        new
                        {
                            Id = 9L,
                            Name = "Finance",
                            NormalizedName = "Finance"
                        });
                });

            modelBuilder.Entity("Domains.Models.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CheckWithTasks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ModifiedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NextTaskIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("PrevTaskIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReadOnlyControls")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequiredControls")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TaskEnumId")
                        .HasColumnType("int");

                    b.Property<int?>("TaskType")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("RoleId");

                    b.ToTable("Task");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NextTaskIds = "2",
                            OrderId = 1,
                            PrevTaskIds = "",
                            ReadOnlyControls = "",
                            RequiredControls = "10",
                            RoleId = 8L,
                            Status = 1,
                            TaskEnumId = 1,
                            TaskType = 2,
                            Title = "Financial Proposal"
                        },
                        new
                        {
                            Id = 2,
                            NextTaskIds = "3",
                            OrderId = 2,
                            PrevTaskIds = "",
                            ReadOnlyControls = "10",
                            RequiredControls = "13",
                            RoleId = 8L,
                            Status = 1,
                            TaskEnumId = 1,
                            TaskType = 2,
                            Title = "Confirmation from Sales Team for Client Approval"
                        },
                        new
                        {
                            Id = 3,
                            NextTaskIds = "4,5",
                            OrderId = 3,
                            PrevTaskIds = "",
                            ReadOnlyControls = "",
                            RequiredControls = "9",
                            RoleId = 8L,
                            Status = 1,
                            TaskEnumId = 3,
                            TaskType = 2,
                            Title = "Technical Proposal"
                        },
                        new
                        {
                            Id = 4,
                            CheckWithTasks = "5",
                            NextTaskIds = "6",
                            OrderId = 4,
                            PrevTaskIds = "3",
                            ReadOnlyControls = "9",
                            RequiredControls = "",
                            RoleId = 4L,
                            Status = 1,
                            TaskEnumId = 4,
                            TaskType = 1,
                            Title = "Design Approval"
                        },
                        new
                        {
                            Id = 5,
                            CheckWithTasks = "4",
                            NextTaskIds = "6",
                            OrderId = 5,
                            PrevTaskIds = "3",
                            ReadOnlyControls = "9",
                            RequiredControls = "",
                            RoleId = 3L,
                            Status = 1,
                            TaskEnumId = 5,
                            TaskType = 1,
                            Title = "Production Approval"
                        },
                        new
                        {
                            Id = 6,
                            NextTaskIds = "7",
                            OrderId = 6,
                            PrevTaskIds = "",
                            ReadOnlyControls = "9",
                            RequiredControls = "",
                            RoleId = 8L,
                            Status = 1,
                            TaskEnumId = 6,
                            TaskType = 2,
                            Title = "Confirmation from Sales Team for Client Approval"
                        },
                        new
                        {
                            Id = 7,
                            CheckWithTasks = "8",
                            NextTaskIds = "9",
                            OrderId = 7,
                            PrevTaskIds = "",
                            ReadOnlyControls = "",
                            RequiredControls = "1,2,3,4,5,6,7",
                            RoleId = 3L,
                            Status = 1,
                            TaskEnumId = 7,
                            TaskType = 2,
                            Title = "Project Initiation"
                        },
                        new
                        {
                            Id = 8,
                            CheckWithTasks = "7",
                            NextTaskIds = "7",
                            OrderId = 8,
                            PrevTaskIds = "",
                            ReadOnlyControls = "",
                            RequiredControls = "",
                            RoleId = 5L,
                            Status = 1,
                            TaskEnumId = 8,
                            TaskType = 2,
                            Title = "Repository"
                        },
                        new
                        {
                            Id = 9,
                            NextTaskIds = "10",
                            OrderId = 9,
                            PrevTaskIds = "7",
                            ReadOnlyControls = "10",
                            RequiredControls = "",
                            RoleId = 9L,
                            Status = 1,
                            TaskEnumId = 9,
                            TaskType = 1,
                            Title = "Finance Team Approval"
                        },
                        new
                        {
                            Id = 10,
                            CheckWithTasks = "11",
                            NextTaskIds = "12",
                            OrderId = 10,
                            PrevTaskIds = "",
                            ReadOnlyControls = "",
                            RequiredControls = "11,14,15,16,17,18,19,20",
                            RoleId = 3L,
                            Status = 1,
                            TaskEnumId = 10,
                            TaskType = 2,
                            Title = "Production"
                        },
                        new
                        {
                            Id = 11,
                            CheckWithTasks = "10",
                            NextTaskIds = "12",
                            OrderId = 11,
                            PrevTaskIds = "",
                            ReadOnlyControls = "9",
                            RequiredControls = "",
                            RoleId = 5L,
                            Status = 1,
                            TaskEnumId = 11,
                            TaskType = 2,
                            Title = "Repository"
                        },
                        new
                        {
                            Id = 12,
                            NextTaskIds = "13",
                            OrderId = 2,
                            PrevTaskIds = "",
                            ReadOnlyControls = "4",
                            RequiredControls = "",
                            RoleId = 6L,
                            Status = 1,
                            TaskEnumId = 12,
                            TaskType = 2,
                            Title = "QC"
                        },
                        new
                        {
                            Id = 13,
                            NextTaskIds = "",
                            OrderId = 13,
                            PrevTaskIds = "12",
                            ReadOnlyControls = "9",
                            RequiredControls = "",
                            RoleId = 9L,
                            Status = 1,
                            TaskEnumId = 13,
                            TaskType = 5,
                            Title = "Finance"
                        });
                });

            modelBuilder.Entity("Domains.Models.UserClaims", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("Domains.Models.UserLogins", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("Domains.Models.UserRoles", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = 1L,
                            RoleId = 1L
                        });
                });

            modelBuilder.Entity("AlmassarGate.Domain.Models.Common.Lookup", b =>
                {
                    b.HasOne("Domains.Models.ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("Domains.Models.ApplicationUser", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedById");
                });

            modelBuilder.Entity("AlmassarGateApi.Domain.Models.Part", b =>
                {
                    b.HasOne("Domains.Models.ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("Domains.Models.ApplicationUser", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedById");
                });

            modelBuilder.Entity("AlmassarGateApi.Domain.Models.ProjectFiles", b =>
                {
                    b.HasOne("Domains.Models.ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("Domains.Models.ApplicationUser", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedById");

                    b.HasOne("Domains.Models.Project", "Project")
                        .WithMany("ProjectFiles")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domains.Models.Action", b =>
                {
                    b.HasOne("Domains.Models.Approval", "Approval")
                        .WithMany()
                        .HasForeignKey("ApprovalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domains.Models.ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("Domains.Models.ApplicationUser", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedById");
                });

            modelBuilder.Entity("Domains.Models.Approval", b =>
                {
                    b.HasOne("Domains.Models.ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("Domains.Models.ApplicationUser", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedById");

                    b.HasOne("Domains.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domains.Models.Task", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domains.Models.AspNetUserTokens", b =>
                {
                    b.HasOne("Domains.Models.ApplicationUser", "User")
                        .WithMany("AspNetUserTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domains.Models.ChecklistAnswer", b =>
                {
                    b.HasOne("Domains.Models.Approval", "Approval")
                        .WithMany()
                        .HasForeignKey("ApprovalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domains.Models.ChecklistQuestion", "ChecklistQuestion")
                        .WithMany()
                        .HasForeignKey("ChecklistQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domains.Models.ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("Domains.Models.ApplicationUser", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedById");
                });

            modelBuilder.Entity("Domains.Models.ChecklistQuestion", b =>
                {
                    b.HasOne("Domains.Models.ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("Domains.Models.ApplicationUser", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedById");
                });

            modelBuilder.Entity("Domains.Models.Group", b =>
                {
                    b.HasOne("Domains.Models.ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("Domains.Models.ApplicationUser", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedById");

                    b.HasOne("Domains.Models.Roles", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domains.Models.Project", b =>
                {
                    b.HasOne("Domains.Models.ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("Domains.Models.ApplicationUser", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedById");
                });

            modelBuilder.Entity("Domains.Models.RoleClaims", b =>
                {
                    b.HasOne("Domains.Models.Roles", "Role")
                        .WithMany("RoleClaims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domains.Models.Task", b =>
                {
                    b.HasOne("Domains.Models.ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("Domains.Models.ApplicationUser", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedById");

                    b.HasOne("Domains.Models.Roles", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domains.Models.UserClaims", b =>
                {
                    b.HasOne("Domains.Models.ApplicationUser", "User")
                        .WithMany("UserClaims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domains.Models.UserLogins", b =>
                {
                    b.HasOne("Domains.Models.ApplicationUser", "User")
                        .WithMany("UserLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domains.Models.UserRoles", b =>
                {
                    b.HasOne("Domains.Models.Roles", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domains.Models.ApplicationUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
